package multiThreading.packt.threadManagement.threadInterruptionControl;

import java.util.concurrent.TimeUnit;

/**
 * Controlling the interruption of a thread
 * */
public class ThreadInterruptionControlSimulator {
    public static void main(String... args) {
        ThreadInterruptionControlFileSearch fileSearch = new ThreadInterruptionControlFileSearch("/home/raj/Programming/Java/DurgaSoft/data", "logs.txt");
        Thread task = new Thread(fileSearch);
        task.setName("ThreadInterruptionControlSimulator");
        task.start();
        try {
            TimeUnit.SECONDS.sleep(10);
        } catch (InterruptedException e) {
            System.out.printf("%s is generated by %s", e.getMessage(), task.getName());
        }
        task.interrupt();
    }
}